### ISSUE TITLE
incorrect link for more detailed blog

### ISSUE THREAD

**Issue by aneesh-joshi** [jeffThompson/Word2VecAndTsne#1]
the blog link
"(For a more detailed tutorial on how to use these scripts, see ****this blog post.*****)" is invalid/ says not found

I suppose the correct link is 
https://www.jeffreythompson.org/blog/2017/02/13/using-word2vec-and-tsne/

**Comment by aneesh-joshi** [comment]
this link reference is in one more place in the Readme

**Comment by jeffThompson** [comment]
Oops, thanks for catching that!
